import { Quote } from "./types";

export const defaultQuotes: Quote[] = [
  {
    id: "q1",
    content: "我们不应该急于求成，我们应该像田野里的麦子，慢慢地生根，慢慢地发芽，在阳光和雨露中，长成属于自己的姿态。",
    author: "林语堂",
    source: "《人生不过如此》",
    category: "人生",
    enabled: true,
    createdAt: 1716470000000,
  },
  {
    id: "q2",
    content: "你如果认识从前的我，也许你会原谅现在的我。",
    author: "张爱玲",
    source: "《倾城之恋》",
    category: "情感",
    enabled: true,
    createdAt: 1716470001000,
  },
  {
    id: "q3",
    content: "一个人只拥有此生此世是不够的，他还应该拥有诗意的世界。",
    author: "王小波",
    source: "《红拂夜奔》",
    category: "诗意",
    enabled: true,
    createdAt: 1716470002000,
  },
  {
    id: "q4",
    content: "如果你要在八月回来，那么我从七月起就会感到很快乐。",
    author: "安托万·德·圣-埃克苏佩里",
    source: "《小王子》",
    category: "陪伴",
    enabled: true,
    createdAt: 1716470003000,
  },
  {
    id: "q5",
    content: "我想要在自己喜欢的领域里，像一棵松树一样，傲然矗立，即使寒冬腊月也能保持着青翠不倒的姿态。",
    author: "钱钟书",
    source: "《围城》",
    category: "志向",
    enabled: true,
    createdAt: 1716470004000,
  },
  {
    id: "q6",
    content: "哪里有阴影，哪里就有光。阴影是光的延伸，是你需要勇敢穿过的温柔黑夜。",
    author: "村上春树",
    source: "《海边的卡夫卡》",
    category: "治愈",
    enabled: true,
    createdAt: 1716470005000,
  },
  {
    id: "q7",
    content: "如果有来生，要做一棵树，站成永恒，没有悲欢的姿势。一半在土里安详，一半在风里飞扬，一半洒落阴凉，一半沐浴阳光。",
    author: "三毛",
    source: "《说给自己听》",
    category: "自由",
    enabled: true,
    createdAt: 1716470006000,
  },
  {
    id: "q8",
    content: "人生中最重要的两个日子，是你出生的那天，和你明白自己为何活着的那天。",
    author: "马克·吐温",
    source: "《随笔》",
    category: "顿悟",
    enabled: true,
    createdAt: 1716470007000,
  },
  {
    id: "q9",
    content: "我不知道将去何方，但我已在路上。",
    author: "宫崎骏",
    source: "《千与千寻》",
    category: "旅途",
    enabled: true,
    createdAt: 1716470008000,
  },
  {
    id: "q10",
    content: "世界这么大，人生这么长，总会有这么一个人，让你想要温柔地对待。",
    author: "宫崎骏",
    source: "《哈尔的移动城堡》",
    category: "温柔",
    enabled: true,
    createdAt: 1716470009000,
  },
  {
    id: "q11",
    content: "即使陷入最黑暗的谷底，也要记得，黑夜终将过去，黎明必会到来，有些花，注定在寒夜中独自绽放。",
    author: "鲁迅",
    source: "《野草》",
    category: "坚毅",
    enabled: true,
    createdAt: 1716470010000,
  },
  {
    id: "q12",
    content: "每个人的心里都有一团火，但路过的人只看到烟。",
    author: "文森特·梵高",
    source: "《梵高传》",
    category: "孤独",
    enabled: true,
    createdAt: 1716470011000,
  },
  {
    id: "q13",
    content: "你走，我不送你；你来，无论多大风多大雨，我要去接你。",
    author: "梁实秋",
    source: "《送行》",
    category: "深情",
    enabled: true,
    createdAt: 1716470012000,
  },
  {
    id: "q14",
    content: "我们倾听时间的声音，像听雪落下来的细碎。在时光的轴线上，今天也是独一无二的刻度。",
    author: "川端康成",
    source: "《雪国》",
    category: "岁月",
    enabled: true,
    createdAt: 1716470013000,
  },
  {
    id: "q15",
    content: "在清晨的咖啡香气中醒来，写下一行无关痛痒的字，原来平淡的日常，也是令人着迷的诗篇。",
    author: "太宰治",
    source: "《女生徒》",
    category: "日常",
    enabled: true,
    createdAt: 1716470014000,
  },
  {
    id: "q16",
    content: "草在结它的种子，风在摇它的叶子，我们站着不说话，就十分美好。",
    author: "顾城",
    source: "《门前》",
    category: "美好",
    enabled: true,
    createdAt: 1716470015000,
  },
  {
    id: "q17",
    content: "黑夜给了我黑色的眼睛，我却用它寻找光明。",
    author: "顾城",
    source: "《一代人》",
    category: "希望",
    enabled: true,
    createdAt: 1716470016000,
  },
  {
    id: "q18",
    content: "生命中所有灿烂终将用寂寞偿还，而我们唯一可以把握的，不过是这片刻的相依与平静。",
    author: "加西亚·马尔克斯",
    source: "《百年孤独》",
    category: "叹叹",
    enabled: true,
    createdAt: 1716470017000,
  },
  {
    id: "q19",
    content: "你瞧，世界依然在有条不紊地转动，每一片飘落的枫叶，都是秋天对大地轻轻写好的情书。",
    author: "叶芝",
    source: "《叶芝诗集》",
    category: "浪漫",
    enabled: true,
    createdAt: 1716470018000,
  },
  {
    id: "q20",
    content: "真正的勇敢，是当你还未开始就已经知道自己会输，可你依然要去做，而且无论如何都要把它坚持到底。",
    author: "哈珀·李",
    source: "《杀死一只知更鸟》",
    category: "勇气",
    enabled: true,
    createdAt: 1716470019000,
  },
  {
    id: "q21",
    content: "愿你生命中有足够多的云翳，来造成一个美丽的黄昏。",
    author: "冰心",
    source: "《寄小读者》",
    category: "祈愿",
    enabled: true,
    createdAt: 1716470020000,
  },
  {
    id: "q22",
    content: "生活是如此宽广，如果你把视线放得足够高，去看看繁星在群山上空闪耀，就会觉得脚下的沟壑其实微不足道。",
    author: "雨果",
    source: "《悲惨世界》",
    category: "辽阔",
    enabled: true,
    createdAt: 1716470021000,
  }
];
